// Generated by dts-bundle-generator v9.5.1

declare const EVENT_FORM_SHOW: "form.show";
declare const EVENT_FORM_SUBMIT: "form.submit";
declare const EVENT_FORM_SUBMITTED: "form.submitted";
declare const EVENT_FORM_CONFIRM: "form.confirm";
declare const EVENT_FORM_STEP_MOVING: "form.step.moving";
declare const EVENT_CONFIRM_SHOW: "confirm.show";
declare const EVENT_CONFIRM_SUBMIT: "confirm.submit";
declare const EVENT_CONFIRM_SUBMITTED: "confirm.submitted";
declare const EVENT_FINISH_SHOW: "finish.show";
declare const EVENT_ERROR_SHOW: "error.show";
declare const EVENT_FORM_FIELD_CHANGE_PREFIX: "form.field.change";
declare const EVENT_FORM_SUBTABLE_FIELD_CHANGE_PREFIX: "form.field.change";
declare const EVENT_FORM_SUBTABLE_ADD_ROW_PREFIX: "form.subtable.addRow";
declare const EVENT_FORM_SUBTABLE_REMOVE_ROW_PREFIX: "form.subtable.removeRow";
declare const EVENT_FORM_KVIEWER_LOOKUP_SELECT_RECORD_PREFIX = "form.kviewerLookup.selectRecord";
declare const EVENT_FORM_KVIEWER_LOOKUP_SELECT_RECORD_IN_SUBTABLE_PREFIX = "form.kviewerLookup.selectRecord";
type FormRecord = {
	[fieldCode: string]: {
		type: string;
		value: unknown;
	};
};
type EventName = typeof EVENT_FORM_SHOW | typeof EVENT_FORM_SUBMIT | typeof EVENT_FORM_SUBMITTED | typeof EVENT_FORM_CONFIRM | typeof EVENT_FORM_STEP_MOVING | typeof EVENT_CONFIRM_SHOW | typeof EVENT_CONFIRM_SUBMIT | typeof EVENT_CONFIRM_SUBMITTED | typeof EVENT_FINISH_SHOW | typeof EVENT_ERROR_SHOW | `${typeof EVENT_FORM_FIELD_CHANGE_PREFIX}.${string}` | `${typeof EVENT_FORM_SUBTABLE_FIELD_CHANGE_PREFIX}.${string}.${string}` | `${typeof EVENT_FORM_SUBTABLE_ADD_ROW_PREFIX}.${string}` | `${typeof EVENT_FORM_SUBTABLE_REMOVE_ROW_PREFIX}.${string}` | `${typeof EVENT_FORM_KVIEWER_LOOKUP_SELECT_RECORD_PREFIX}.${string}` | `${typeof EVENT_FORM_KVIEWER_LOOKUP_SELECT_RECORD_IN_SUBTABLE_PREFIX}.${string}.${string}`;
type EventData<E extends string> = E extends `${typeof EVENT_FORM_SUBTABLE_ADD_ROW_PREFIX}.${string}` ? {
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/** フィールドに値を設定する関数 */
	setFieldValue: (
		/** 値を設定するフィールドのフィールドコード */
		fieldCode: string,
		/** 設定する値 */
		value: unknown) => void;
	/** テーブル内フィールドに値を設定する関数 */
	setSubtableFieldValue: (
		/** 値を設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** 値を設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** 値を設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/** 設定する値 */
		value: unknown) => void;
	/** フィールドにエラーメッセージを設定する関数 */
	setFieldValueError: (
		/** エラーメッセージを設定するフィールドのフィールドコード */
		fieldCode: string,
		/**
		 * 設定するエラーメッセージ
		 *
		 * エラーメッセージを設定済みのフィールドに対してエラーメッセージをクリアする場合は値にnullを設定してください。
		 */
		errorMessage: string | null) => void;
	/** テーブル内フィールドにエラーメッセージを設定する関数 */
	setSubtableFieldValueError: (
		/** エラーメッセージを設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** エラーメッセージを設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** エラーメッセージを設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/**
		 * 設定するエラーメッセージ
		 *
		 * エラーメッセージを設定済みのフィールドに対してエラーメッセージをクリアする場合は値にnullを設定してください。
		 */
		errorMessage: string | null) => void;
	/**
	 * 行追加をキャンセルする関数
	 *
	 * イベントハンドラ内で呼び出すことで行の追加をキャンセルすることができます。
	 */
	preventDefault: () => void;
	/** 追加される行のデータ */
	newRow: {
		value: FormRecord;
	};
} : E extends `${typeof EVENT_FORM_SUBTABLE_REMOVE_ROW_PREFIX}.${string}` ? {
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/** フィールドに値を設定する関数 */
	setFieldValue: (
		/** 値を設定するフィールドのフィールドコード */
		fieldCode: string,
		/** 設定する値 */
		value: unknown) => void;
	/** テーブル内フィールドに値を設定する関数 */
	setSubtableFieldValue: (
		/** 値を設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** 値を設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** 値を設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/** 設定する値 */
		value: unknown) => void;
	/** フィールドにエラーメッセージを設定する関数 */
	setFieldValueError: (
		/** エラーメッセージを設定するフィールドのフィールドコード */
		fieldCode: string,
		/**
		 * 設定するエラーメッセージ
		 *
		 * エラーメッセージを設定済みのフィールドに対してエラーメッセージをクリアする場合は値にnullを設定してください。
		 */
		errorMessage: string | null) => void;
	/** テーブル内フィールドにエラーメッセージを設定する関数 */
	setSubtableFieldValueError: (
		/** エラーメッセージを設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** エラーメッセージを設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** エラーメッセージを設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/**
		 * 設定するエラーメッセージ
		 *
		 * エラーメッセージを設定済みのフィールドに対してエラーメッセージをクリアする場合は値にnullを設定してください。
		 */
		errorMessage: string | null) => void;
	/**
	 * 行削除をキャンセルする関数
	 *
	 * イベントハンドラ内で呼び出すことで行の削除をキャンセルすることができます。
	 */
	preventDefault: () => void;
	/** 削除される行の番号(0始まり) */
	rowIndex: number;
} : E extends `${typeof EVENT_FORM_SUBTABLE_FIELD_CHANGE_PREFIX}.${string}.${string}` ? {
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/** フィールドに値を設定する関数 */
	setFieldValue: (
		/** 値を設定するフィールドのフィールドコード */
		fieldCode: string,
		/** 設定する値 */
		value: unknown) => void;
	/** テーブル内フィールドに値を設定する関数 */
	setSubtableFieldValue: (
		/** 値を設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** 値を設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** 値を設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/** 設定する値 */
		value: unknown) => void;
	/** フィールドにエラーメッセージを設定する関数 */
	setFieldValueError: (
		/** エラーメッセージを設定するフィールドのフィールドコード */
		fieldCode: string,
		/**
		 * 設定するエラーメッセージ
		 *
		 * エラーメッセージを設定済みのフィールドに対してエラーメッセージをクリアする場合は値にnullを設定してください。
		 */
		errorMessage: string | null) => void;
	/** テーブル内フィールドにエラーメッセージを設定する関数 */
	setSubtableFieldValueError: (
		/** エラーメッセージを設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** エラーメッセージを設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** エラーメッセージを設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/**
		 * 設定するエラーメッセージ
		 *
		 * エラーメッセージを設定済みのフィールドに対してエラーメッセージをクリアする場合は値にnullを設定してください。
		 */
		errorMessage: string | null) => void;
	/**
	 * 値の変更をキャンセルする関数
	 *
	 * イベントハンドラ内で呼び出すことで値の変更をキャンセルできます。setSubtableFieldValue でイベントハンドラを登録したテーブル内フィールドの値を変更したときに呼び出してください。
	 */
	preventDefault: () => void;
	/** 値が変更された行番号(0始まり) */
	rowIndex: number;
	/** 変更後の値 */
	value: unknown;
} : E extends `${typeof EVENT_FORM_FIELD_CHANGE_PREFIX}.${string}` ? {
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/** フィールドに値を設定する関数 */
	setFieldValue: (
		/** 値を設定するフィールドのフィールドコード */
		fieldCode: string,
		/** 設定する値 */
		value: unknown) => void;
	/** テーブル内フィールドに値を設定する関数 */
	setSubtableFieldValue: (
		/** 値を設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** 値を設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** 値を設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/** 設定する値 */
		value: unknown) => void;
	/** フィールドにエラーメッセージを設定する関数 */
	setFieldValueError: (
		/** エラーメッセージを設定するフィールドのフィールドコード */
		fieldCode: string,
		/**
		 * 設定するエラーメッセージ
		 *
		 * エラーメッセージを設定済みのフィールドに対してエラーメッセージをクリアする場合は値にnullを設定してください。
		 */
		errorMessage: string | null) => void;
	/** テーブル内フィールドにエラーメッセージを設定する関数 */
	setSubtableFieldValueError: (
		/** エラーメッセージを設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** エラーメッセージを設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** エラーメッセージを設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/**
		 * 設定するエラーメッセージ
		 *
		 * エラーメッセージを設定済みのフィールドに対してエラーメッセージをクリアする場合は値にnullを設定してください。
		 */
		errorMessage: string | null) => void;
	/**
	 * 値の変更をキャンセルする関数
	 *
	 * イベントハンドラ内で呼び出すことで値の変更をキャンセルできます。setFieldValue でイベントハンドラを登録したフィールドの値を変更したときに呼び出してください。
	 */
	preventDefault: () => void;
	/** 変更後の値 */
	value: unknown;
} : E extends `${typeof EVENT_FORM_KVIEWER_LOOKUP_SELECT_RECORD_IN_SUBTABLE_PREFIX}.${string}.${string}` ? {
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/** フィールドに値を設定する関数 */
	setFieldValue: (
		/** 値を設定するフィールドのフィールドコード */
		fieldCode: string,
		/** 設定する値 */
		value: unknown) => void;
	/** テーブル内フィールドに値を設定する関数 */
	setSubtableFieldValue: (
		/** 値を設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** 値を設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** 値を設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/** 設定する値 */
		value: unknown) => void;
	/** フィールドにエラーメッセージを設定する関数 */
	setFieldValueError: (
		/** エラーメッセージを設定するフィールドのフィールドコード */
		fieldCode: string,
		/**
		 * 設定するエラーメッセージ
		 *
		 * エラーメッセージを設定済みのフィールドに対してエラーメッセージをクリアする場合は値にnullを設定してください。
		 */
		errorMessage: string | null) => void;
	/** テーブル内フィールドにエラーメッセージを設定する関数 */
	setSubtableFieldValueError: (
		/** エラーメッセージを設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** エラーメッセージを設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** エラーメッセージを設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/**
		 * 設定するエラーメッセージ
		 *
		 * エラーメッセージを設定済みのフィールドに対してエラーメッセージをクリアする場合は値にnullを設定してください。
		 */
		errorMessage: string | null) => void;
	/**
	 * 選択されたレコードをテーブル内のフィールドにセットする処理をキャンセルする関数
	 *
	 * イベントハンドラ内でこの関数を呼び出すことで選択されたレコードを同じ行内のフィールドに反映する処理がキャンセルされます。
	 */
	preventDefault: () => void;
	/** kViewer Lookup によるレコードの選択が行われたテーブルの行番号(0始まり) */
	rowIndex: number;
	/** kViewerルックアップフィールドのダイアログ上で選択されたkintoneレコードを取得する関数 */
	getSelectedKintoneRecord: () => unknown;
} : E extends `${typeof EVENT_FORM_KVIEWER_LOOKUP_SELECT_RECORD_PREFIX}.${string}` ? {
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/** フィールドに値を設定する関数 */
	setFieldValue: (
		/** 値を設定するフィールドのフィールドコード */
		fieldCode: string,
		/** 設定する値 */
		value: unknown) => void;
	/** テーブル内フィールドに値を設定する関数 */
	setSubtableFieldValue: (
		/** 値を設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** 値を設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** 値を設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/** 設定する値 */
		value: unknown) => void;
	/** フィールドにエラーメッセージを設定する関数 */
	setFieldValueError: (
		/** エラーメッセージを設定するフィールドのフィールドコード */
		fieldCode: string,
		/**
		 * 設定するエラーメッセージ
		 *
		 * エラーメッセージを設定済みのフィールドに対してエラーメッセージをクリアする場合は値にnullを設定してください。
		 */
		errorMessage: string | null) => void;
	/** テーブル内フィールドにエラーメッセージを設定する関数 */
	setSubtableFieldValueError: (
		/** エラーメッセージを設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** エラーメッセージを設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** エラーメッセージを設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/**
		 * 設定するエラーメッセージ
		 *
		 * エラーメッセージを設定済みのフィールドに対してエラーメッセージをクリアする場合は値にnullを設定してください。
		 */
		errorMessage: string | null) => void;
	/**
	 * 選択されたレコードをフォーム上のフィールドにセットする処理をキャンセルする関数
	 *
	 * イベントハンドラ内でこの関数を呼び出すことで選択されたレコードを回答データに反映する処理がキャンセルされます。
	 */
	preventDefault: () => void;
	/** kViewerルックアップフィールドのダイアログ上で選択されたkintoneレコードを取得する関数 */
	getSelectedKintoneRecord: () => unknown;
} : E extends typeof EVENT_FORM_SHOW ? {
	/** 現在表示しているステップ番号(ステップフォーム設定時のみ) */
	currentStep?: number;
	/** 現在表示する一つ前のステップ番号(ステップフォーム設定時のみ) */
	previousStep?: number | null;
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/** フィールドに値を設定する関数 */
	setFieldValue: (
		/** 値を設定するフィールドのフィールドコード */
		fieldCode: string,
		/** 設定する値 */
		value: unknown) => void;
	/** テーブル内フィールドに値を設定する関数 */
	setSubtableFieldValue: (
		/** 値を設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** 値を設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** 値を設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/** 設定する値 */
		value: unknown) => void;
} : E extends typeof EVENT_FORM_SUBMIT ? {
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/** フィールドに値を設定する関数 */
	setFieldValue: (
		/** 値を設定するフィールドのフィールドコード */
		fieldCode: string,
		/** 設定する値 */
		value: unknown) => void;
	/** テーブル内フィールドに値を設定する関数 */
	setSubtableFieldValue: (
		/** 値を設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** 値を設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** 値を設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/** 設定する値 */
		value: unknown) => void;
	/**
	 * 回答処理をキャンセルする関数
	 *
	 * この関数をイベントハンドラ内で呼び出すと回答処理がキャンセルされ、回答画面に留まります。
	 */
	preventDefault: () => void;
} : E extends typeof EVENT_FORM_SUBMITTED ? {
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/**
	 * 完了画面への遷移をキャンセルする関数
	 *
	 * この関数をイベントハンドラ内で呼び出すと完了画面への遷移がキャンセルされます。特に完了画面を表示せずに別のページを表示したいときに利用できます。
	 */
	preventDefault: () => void;
} : E extends typeof EVENT_FORM_CONFIRM ? {
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/** フィールドに値を設定する関数 */
	setFieldValue: (
		/** 値を設定するフィールドのフィールドコード */
		fieldCode: string,
		/** 設定する値 */
		value: unknown) => void;
	/** テーブル内フィールドに値を設定する関数 */
	setSubtableFieldValue: (
		/** 値を設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** 値を設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** 値を設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/** 設定する値 */
		value: unknown) => void;
	/**
	 * 確認画面への遷移をキャンセルする関数
	 *
	 * この関数をイベントハンドラ内で呼び出すと確認画面への遷移がキャンセルされ、表示中の回答画面に留まります。
	 */
	preventDefault: () => void;
} : E extends typeof EVENT_FORM_STEP_MOVING ? {
	/** 現在表示しているステップ番号 */
	currentStep: number;
	/** 次に表示しようとしているステップ番号 */
	nextStep: number;
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/** フィールドに値を設定する関数 */
	setFieldValue: (
		/** 値を設定するフィールドのフィールドコード */
		fieldCode: string,
		/** 設定する値 */
		value: unknown) => void;
	/** テーブル内フィールドに値を設定する関数 */
	setSubtableFieldValue: (
		/** 値を設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** 値を設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** 値を設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/** 設定する値 */
		value: unknown) => void;
	/**
	 * 次のステップ画面への遷移をキャンセルする関数
	 *
	 * この関数をイベントハンドラ内で呼び出すと次のステップ画面への遷移がキャンセルされ、現在のステップ画面に留まります。
	 */
	preventDefault: () => void;
} : E extends typeof EVENT_CONFIRM_SHOW ? {
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/** フィールドに値を設定する関数 */
	setFieldValue: (
		/** 値を設定するフィールドのフィールドコード */
		fieldCode: string,
		/** 設定する値 */
		value: unknown) => void;
	/** テーブル内フィールドに値を設定する関数 */
	setSubtableFieldValue: (
		/** 値を設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** 値を設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** 値を設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/** 設定する値 */
		value: unknown) => void;
} : E extends typeof EVENT_CONFIRM_SUBMIT ? {
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/** フィールドに値を設定する関数 */
	setFieldValue: (
		/** 値を設定するフィールドのフィールドコード */
		fieldCode: string,
		/** 設定する値 */
		value: unknown) => void;
	/** テーブル内フィールドに値を設定する関数 */
	setSubtableFieldValue: (
		/** 値を設定するテーブルフィールドのフィールドコード */
		tableFieldCode: string,
		/** 値を設定するテーブル内フィールドのフィールドコード */
		fieldCode: string,
		/** 値を設定するフィールドが含まれる行の番号(0始まり) */
		rowIndex: number,
		/** 設定する値 */
		value: unknown) => void;
	/**
	 * 回答処理をキャンセルする関数
	 *
	 * この関数をイベントハンドラ内で呼び出すと回答処理がキャンセルされ、確認画面に留まります。
	 */
	preventDefault: () => void;
} : E extends typeof EVENT_CONFIRM_SUBMITTED ? {
	/**
	 * イベントハンドラ呼び出し時の回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
	/**
	 * 完了画面への遷移をキャンセルする関数
	 *
	 * この関数をイベントハンドラ内で呼び出すと完了画面への遷移がキャンセルされます。特に完了画面を表示せずに別のページを表示したいときに利用できます。
	 */
	preventDefault: () => void;
} : E extends typeof EVENT_FINISH_SHOW ? {
	/**
	 * 回答内容を取得する関数
	 *
	 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.getRecord` を使用してください。
	 */
	getRecord: () => FormRecord;
} : E extends typeof EVENT_ERROR_SHOW ? null : never;
declare class FormBridgeEventTarget extends EventTarget {
	/**
	 * フォームのカスタマイズイベントを登録する。
	 *
	 * 指定したイベントが発生した際にコールバックが実行されます。
	 * 例:
	 * ```ts
	 * formBridge.events.on('form.show', (ctx) => { ... });
	 * ```
	 */
	on<E extends EventName>(eventName: E, callback: (context: EventData<E>) => void): void;
}
type FormFieldSettingBase = {
	code: string;
	label: string;
	help: string;
	isEditable: boolean;
	isHide: boolean;
	isHideLabel: boolean;
	isHideMobile: boolean;
	isRequired: boolean;
	expression: string;
	maxLength: null | number;
	maxValue: null | number;
	minLength: null | number;
	minValue: null | number;
	multiLineRows: null | number;
	optionOrder: "horizontal" | "vertical";
	options: string[];
	protocol: string;
	step: number;
	useThousandsSeparator: null | boolean;
	defaultValue: unknown;
	lookup: unknown;
	addressFieldMappings: unknown[];
};
type FormFieldSetting = FormFieldSettingBase & {
	tableFields: (FormFieldSettingBase & {
		width: string;
		parentCode: string;
	})[];
};
type MutableFieldSettings = {
	/** 選択肢 */
	name: "options";
	value: string[];
};
type MutableFieldSettingName = MutableFieldSettings["name"];
type MutableFieldSettingValueOf<N extends MutableFieldSettingName> = Extract<MutableFieldSettings, {
	name: N;
}>["value"];
declare global {
	/**
	 * フォームページの実行時に自動で提供されるグローバル変数
	 *
	 * JavaScript カスタマイズコードからフォームのイベント登録や操作を行う際に使用します.
	 */
	const formBridge: {
		/**
		 * カスタマイズ用イベントAPIの名前空間
		 */
		events: FormBridgeEventTarget;
		/**
		 * フォーム関数を提供する名前空間
		 */
		fn: {
			/**
			 * フォームの回答データを取得する関数
			 *
			 * フィールドの値変更イベント("form.field.change." から始まるイベント)のハンドラ内では変更前の値を取得できます。変更後の値はイベント引数の value を参照してください。
			 */
			getRecord: () => {
				[fieldCode: string]: {
					/** フィールドタイプ */
					type: string;
					/** フィールドの値 */
					value: unknown;
				};
			};
			/**
			 * フィールドの設定データを取得する関数
			 *
			 * 回答画面(通常の入力画面, ステップフォーム画面)でのみ利用可能です。確認画面および完了画面で実行すると例外が発生します。
			 */
			getFieldSettings: () => FormFieldSetting[];
			/**
			 * フィールドの設定を更新する関数
			 *
			 * @param fieldCode 更新対象のフィールドのコード
			 * @param settingName 更新する設定項目の名前（'options' など）
			 * @param settingValue 設定項目に対応する値
			 */
			updateFieldSetting: <N extends MutableFieldSettingName>(fieldCode: string, settingName: N, settingValue: MutableFieldSettingValueOf<N>) => void;
			/**
			 * テーブル内フィールドの設定を更新する関数
			 *
			 * @param parentFieldCode 更新対象のフィールドが配置されているテーブルフィールドのフィールドコード
			 * @param fieldCode 更新対象のテーブル内フィールドのコード
			 * @param settingName 更新する設定項目の名前（'options' など）
			 * @param settingValue 設定項目に対応する値
			 */
			updateFieldInSubtableSetting: <N extends MutableFieldSettingName>(parentFieldCode: string, fieldCode: string, settingName: N, settingValue: MutableFieldSettingValueOf<N>) => void;
			/**
			 * フォームの回答処理を実行する関数
			 *
			 * 回答画面(通常の入力画面, ステップフォーム画面)および確認画面でのみ利用可能です。完了画面で実行すると例外が発生します。
			 */
			emitSubmit: () => void;
		};
		/**
		 * フォームの回答処理を実行する関数
		 *
		 * @deprecated 後方互換のために残されています。代わりに `formBridge.fn.emitSubmit` を使用してください。
		 */
		emitSubmit: () => void;
	};
}

export { };
